# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d243dd3efb6f187c1b04a45119b69bebb05a7e87614f17bde15658ce3d1243a36e86bc8c9e5174c4aa4341688d57eddb5f34f78ccf258863c151a7a73726119d

test:
  secret_key_base: 6d7abb4e9d3fb0e5ceda593c150b00edad539bfae872de1447623c5bc4a9ad9167868f446b85d0ac52e1590f200e46a883efdddc36b48a299ae57283488226f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
